### ISSUE TITLE
TNT 2.0 - TransportCallId in Event object ?

### ISSUE THREAD

**Issue by rgenoulaz** [dcsaorg/DCSA-OpenAPI#12]
Hi, 
I may have missed something but I do not understand why we now have a TransportCallId in Event objet.
Considering that an event object mught not me related to a specific call ( for example Shipment event, like a booking confirmation) I have to say I'm a bit confused.

Can you please clarify ?

Thanks

**Comment by AsgerStage** [comment]
Hi Romain,

I have reached out to @raisoman to also get his perspective on this, as he knows more about this than I do.

My impression is that in IM 2.0, which includes OVS, all events are related to a Transport Call. Without reference to that, you lack a lot of information, such as the location of the event.

In T&T 1.x.x, transport calls don't exist, and the events themselves contain the location information.

Best,
Asger

**Comment by raisoman** [comment]
I would agree with @rgenoulaz .

Not sure how transportCallId sneaked into Event, since it is already on TransportEvent and EquipmentEvent and isn't part of Event in the [interface standard (p.16-17)](https://dcsa.org/data-and-interfaces/interface-standard-for-track-and-trace-v1-2/) .

I am not sure that Event should be part of the swagger spec at all, since it's purely abstract.

**Comment by rgenoulaz** [comment]
OK thanks, 
I would keep Event but remove TransportCallId.
By the way, I guess and Id it shouldnt have been a "number" type don't you think ?
Personnaly I prefer using strings for Ids (in swagger definitions).

**Comment by AsgerStage** [comment]
Hi Romain,

Thanks for the feedback. I agree, it should have been a string. 
I have added your suggestions to #13
