### ISSUE TITLE
Date Time fields not mandated in Transport Events

### ISSUE THREAD

**Issue by jasil1414** [dcsaorg/DCSA-OpenAPI#131]
Hi DCSA team,
For Transport event in page number 30 of the document [DCSA Interface Standard for Track and
Trace](https://dcsa.org/wp-content/uploads/2021/10/202110_DCSA_P1_Interface-Standard-for-Track-and-Trace-2.2_Final.pdf) does **not** mandate below fields which seems to be incorrect.

- Event Created DateTime
- Event DateTime
- Event Classifier Code

<img width="702" alt="Screenshot 2022-01-21 at 6 17 01 PM" src="https://user-images.githubusercontent.com/21127867/150529464-37565fd4-4361-47ee-8afb-3017b5132d0c.png">

Thanks,

**Comment by HenrikHL** [comment]
Hi @jasil1414 thank you for noticing this.
I have informed the responsible person for [DCSA Interface Standard for Track and
Trace](https://dcsa.org/wp-content/uploads/2021/10/202110_DCSA_P1_Interface-Standard-for-Track-and-Trace-2.2_Final.pdf) to please update it with correctly defined mandatory fields (*).
Also please note that the ID field of the `TransportEvent` is called `eventID` and not `transportEventID`
The API for T&T defined here should be used: https://app.swaggerhub.com/apis/dcsaorg/DCSA_TNT

**Comment by HenrikHL** [comment]
Hi again @jasil1414 P4 team (responsible for the [DCSA Interface Standard for Track and Trace](https://dcsa.org/wp-content/uploads/2021/10/202110_DCSA_P1_Interface-Standard-for-Track-and-Trace-2.2_Final.pdf) have informed me that this will be fixed in the next version.
If you have any other concerns please don't hesitate to contact us - closing this for now
