### ISSUE TITLE
Getting (only) amended content

### ISSUE THREAD

**Issue by RowlandShaw** [dcsaorg/DCSA-OpenAPI#397]
The [GET method for Bookings](https://app.swaggerhub.com/apis-docs/dcsaorg/DCSA_BKG/2.0.0#/Booking/get-bookings) defines a boolean amendedContent parameter, however it's not clear if this is intended to show:
* All changes to the booking since the booking was queried by that client
* All changes to the booking since any API consumer queries that booking
* Only changes in the most recent update to the given booking made by any API consumer

It feels like it would be less fragile to mandate that implementations always provided the current state of the booking - or a 404 if the booking is not known or other business rules define that the client making the request should not be able to see details of a given bill. 

I think the security aspect is key if implementations are out in the wild that work by bill of lading number, as those could be brute forced by a bad actor to get details of bookings that they shouldn't have visibility of - for example, a malicious forwarder could "accidentally" query bookings or bills other than the ones with them and solicit information they shouldn't have - whilst this would be a clear breach of competition law, it still feels like something a responsible implementor would want to guard against, and still return a 404 response.

**Comment by HenrikHL** [comment]
Hi @RowlandShaw,

It is correct that on the

    GET /v2/bookings/{carrierBookingReference}

it is possible to add a `amendedContent` queryParameter specifying that the response payload should contain (if possible) an ongoing amendment payload.
To answer your question - using this queryParameter returns:
- Only changes in the most recent update to the given booking made by any API consumer

Calling the GET endPoint **without** a queryParameter returns the latest "agreed" Booking between consumer and provider. In case a Booking is CONFIRMED - it **always** returns the latest CONFIRMED booking. In case it is not yet CONFIRMED - it returns the latest agreed Booking (no matter the state).
Calling the GET endPoint **with** the `amendedContent` queryParameter returns a possible amendment. The amendment can be accepted, rejected, cancelled or "ongoing". A diff between the amendment and the "active" Booking would show the changes being requested. If no amendment has yet been requested - using the queryParameter would return a `404` (Not Found).

Once the update is accepted - it becomes the "new" confirmed booking.
**Note:** It is _**not**_ possible to update an update. If this is needed then either: the update needs to be cancelled or once the update is accepted/rejected by provider - a new update needs to be sent.

Please note that it is not possible to use a `Bill of Lading number` (which in DCSA standards is called `transportDocumentReference`) in the Booking API. `Bill of Lading number` is only usable in the EBL API (in `Shipping Instructions` and `Transport Document` endPoints)

In order to query Booking and EBL endPoints the caller must be Authenticated in the provider system. On top of Authentication - Authorization should also be in place by providers once Authenticated. This will only allow a consumer to access Bookings and Bill of Ladings accessible to him/her.
It is out-of-scope for DCSA to prevent internal brute-force-attacks. I am sure providers have internal procedures for preventing this ;-)

If it helps - I would be glad to take an online call explaining the process.

**Comment by RowlandShaw** [comment]
Ah, so I've gone down the wrong rabbit hole, and should be trying to find the [transport document specs](https://developer.dcsa.org/implementing-bill-of-lading-si-td) :)

**Comment by HenrikHL** [comment]
@RowlandShaw saw you closed this issue yesterday - just want to make you aware of the above comment ;-)

**Comment by RowlandShaw** [comment]
For the use case I'm considering @HenrikHL  - this is all about the consignee wanting to arrange delivery on a through bill; So, let's suggest that a sample bill of lading had a container loading in Boston, and discharging Felixstowe has carriage prepaid through to Doncaster; the consignee is wanting to make contact with the carrier to arrange the exact address, provide tip references, arrange an appointment time, etc. - there's not enough detail on the Booking API, and from the Shipping Instructions point of view, the bill has already been issued, so that feels wrong too?

It's not clear which DCSA API is intended for that scenario (and this was my motivation for raising the more focused #398)
